### ISSUE TITLE
hi i am your  studint in udacity the chat is going down i really hope we can conntact in other way maybe linked in facebook 

### ISSUE THREAD

**Issue by GalalMagdySafwat** [rajtheinnovator/BakingAgain-Galal-EspressoIdlingTestSolution#1]

**Comment by GalalMagdySafwat** [comment]
reply any time

**Comment by rajtheinnovator** [comment]
Hi Galal @GalalMagdySafwat, can you please ask your question at my LinkedIn profile here: https://www.linkedin.com/in/iamabhishekraj/ until this chat issue is resolved. I'll try to respond back at the earliest. 

And I really apologize for the inconvenience caused. We all mentors have already reported the issues but it's still not resolved. Let's hope that it's fixed soon.

**Comment by GalalMagdySafwat** [comment]
https://www.linkedin.com/in/galal-magdy-0b289311a/ 
this is my account i cant send you a msg until you add me i think i send you a request so anyway this is my profile
